fix(tests): "provider#python3#Prog" was removed upstream
Problem:
Tests fail since upstream Nvim commit https://github.com/neovim/neovim/commit/eb5d15e3838f53e2fcd25989c88db87458e9f984
which removed the (internal) `provider#python3#Prog` function.

    pynvim.api.common.NvimError: nvim_exec2(): Vim(echomsg):E117: Unknown function: provider#python3#Prog

Solution:
Use the new Lua function instead.