ci: fix failing readthedocs build
Running Sphinx v7.2.6
making output directory... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynvim/envs/latest/lib/python3.11/site-packages/sphinx/cmd/build.py", line 293, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynvim/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 272, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynvim/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 342, in _init_builder
    self.builder.init()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynvim/envs/latest/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 219, in init
    self.init_templates()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynvim/envs/latest/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 270, in init_templates
    self.theme = theme_factory.create(themename)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/pynvim/envs/latest/lib/python3.11/site-packages/sphinx/theming.py", line 230, in create
    raise ThemeError(__('no theme named %r found (missing theme.conf?)') % name)
sphinx.errors.ThemeError: no theme named 'sphinx_rtd_theme' found (missing theme.conf?)

Theme error:
no theme named 'sphinx_rtd_theme' found (missing theme.conf?)0j0gZZ